### ISSUE TITLE
window:AddEventHandler("event", "Handler") does not work for windows created by GeminiGUI

### ISSUE THREAD

**Issue by TomVarga** [wildstarnasa/GeminiGUI#1]
You can use the following example addon to verify the following issue:

When you create a window with GeminiGUI and try to add an event handler to it such as "WindowMove" it won't work, where else if you create the same window from XML it'll work just fine.

https://drive.google.com/file/d/0B5Hgmr1RAr3NSTJxb3VDUzBvZHM/edit?usp=sharing

**Comment by Sinaloit** [comment]
Passing self to GetInstance would resolve this, the problem is that GetInstance's 1st param is the eventHandler table.  If none is provided it creates one, but never returns any reference to it, so you have no way of adding an event handler to that table.  Most likely GetInstance should return both the instance and a reference to the eventHandler table.  Most code is only anticipating 1 return value so this should be a non-breaking change.  Will need to look over the code and see if there are any other similar issues.  Alernate suggestions accepted!

Example working way:

``` lua
function MyAddon:OnEnable()
    local wndRef = tMyGeminiGuiWidget:GetInstance(self)
    wndRef:AddEventHandler("Event", "OnEvent")
end

function MyAddon:OnEvent()
    Print("Event Happened!")
end
```
